### ISSUE TITLE
fatal error install no openssl.h

### ISSUE THREAD

**Issue by rancheng** [Wiggyboy/keyring-unlock#1]
please add this line to your readme:

```sh
sudo apt install libsssl-dev
```

**Comment by Olindholm** [comment]
I'm assuming you mean **libssl-dev**.

However I don't know/see why this is required or helpful. I don't the package it installed and the script works fine. Could you elaborate on your issue.

* What is the error, when is it occurring?
* What distribution and version are you running?
* What package for the keyring are you using?

Thanks :)

**Comment by rancheng** [comment]
Thanks for correction, it's `libssl-dev` needed by the following line:

```sh
pip3 install keyring
```
wheel need openssl to build keyring.

**Comment by Olindholm** [comment]
I can't find any requirements or dependencies to back this up.

Because of the lack of further information that I requested I cannot look further into this. It's working fine on multiple of my devices without this package. Therefore I must deem to not fix this until further reports of this problem.
